import { CodeBlock } from "../CodeBlock";

export function PackageYml() {
  return (
    <section id="package-yml" className="scroll-mt-20">
      <h2 className="text-2xl font-bold tracking-tight mb-2">package.yml</h2>
      <p className="text-muted-foreground mb-6">
        The project manifest &mdash; equivalent to npm's{" "}
        <code className="bg-muted px-1 py-0.5 rounded text-xs">
          package.json
        </code>
        . Created by{" "}
        <code className="bg-muted px-1 py-0.5 rounded text-xs">pypmc init</code>{" "}
        and updated automatically when you install or remove packages.
      </p>

      <CodeBlock
        title="package.yml"
        code={`name: my-project
version: 1.0.0
description: A sample Python project
author: Jane Doe
license: MIT
python: ">=3.8"

scripts:
  start: python main.py
  test: pytest
  lint: flake8 src/

dependencies:
  requests: "==2.31.0"
  flask: "==3.0.0"

dev_dependencies:
  pytest: "==8.0.0"
  flake8: "==7.0.0"`}
        language="yaml"
      />

      <h3 className="text-base font-semibold mt-6 mb-3">Fields</h3>
      <div className="overflow-x-auto">
        <table className="w-full text-sm border border-border rounded-lg overflow-hidden">
          <thead>
            <tr className="bg-muted/50">
              <th className="text-left px-4 py-2 font-medium">Field</th>
              <th className="text-left px-4 py-2 font-medium">Required</th>
              <th className="text-left px-4 py-2 font-medium">Description</th>
            </tr>
          </thead>
          <tbody>
            {[
              ["name", "Yes", "Project name"],
              ["version", "Yes", "Semantic version string"],
              ["description", "No", "Brief project description"],
              ["author", "No", "Author name"],
              ["license", "No", "SPDX license identifier (default: MIT)"],
              ["python", "No", "Required Python version specifier"],
              ["scripts", "No", "Named shell commands (like npm scripts)"],
              [
                "dependencies",
                "No",
                "Production dependencies with version pins",
              ],
              ["dev_dependencies", "No", "Development-only dependencies"],
            ].map(([field, req, desc]) => (
              <tr key={field} className="border-t border-border">
                <td className="px-4 py-2 font-mono text-xs">{field}</td>
                <td className="px-4 py-2">{req}</td>
                <td className="px-4 py-2 text-muted-foreground">{desc}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

export function Lockfile() {
  return (
    <section id="lockfile" className="scroll-mt-20">
      <h2 className="text-2xl font-bold tracking-tight mb-2">
        package-lock.yml
      </h2>
      <p className="text-muted-foreground mb-6">
        The lockfile captures the exact installed version of every package
        (including transitive dependencies) for reproducible builds. It is
        regenerated automatically after every install, uninstall, or update
        operation.
      </p>

      <CodeBlock
        title="package-lock.yml"
        code={`lockfile_version: 1

packages:
  certifi:
    version: "2024.2.2"
  charset-normalizer:
    version: "3.3.2"
  flask:
    version: "3.0.0"
  idna:
    version: "3.6"
  requests:
    version: "2.31.0"
  urllib3:
    version: "2.1.0"
  werkzeug:
    version: "3.0.1"
  jinja2:
    version: "3.1.3"
  markupsafe:
    version: "2.1.5"
  itsdangerous:
    version: "2.1.2"
  click:
    version: "8.1.7"
  blinker:
    version: "1.7.0"`}
        language="yaml"
      />

      <h3 className="text-base font-semibold mt-6 mb-3">How it works</h3>
      <ul className="list-disc list-inside space-y-2 text-sm text-muted-foreground">
        <li>
          Generated by querying{" "}
          <code className="bg-muted px-1 py-0.5 rounded text-xs">
            pip list --format=json
          </code>{" "}
          inside the venv after each operation.
        </li>
        <li>
          Internal packages (
          <code className="bg-muted px-1 py-0.5 rounded text-xs">pip</code>,{" "}
          <code className="bg-muted px-1 py-0.5 rounded text-xs">
            setuptools
          </code>
          , <code className="bg-muted px-1 py-0.5 rounded text-xs">wheel</code>)
          are excluded.
        </li>
        <li>
          When{" "}
          <code className="bg-muted px-1 py-0.5 rounded text-xs">
            pypmc install
          </code>{" "}
          is run without arguments, the lockfile takes priority over package.yml
          &mdash; ensuring exact version reproduction.
        </li>
        <li>
          <strong className="text-foreground">Always commit this file</strong>{" "}
          to version control so teammates and CI get identical environments.
        </li>
      </ul>
    </section>
  );
}

export function Scripts() {
  return (
    <section id="scripts" className="scroll-mt-20">
      <h2 className="text-2xl font-bold tracking-tight mb-2">Scripts</h2>
      <p className="text-muted-foreground mb-6">
        Define reusable shell commands in the{" "}
        <code className="bg-muted px-1 py-0.5 rounded text-xs">scripts</code>{" "}
        section of package.yml, then run them with{" "}
        <code className="bg-muted px-1 py-0.5 rounded text-xs">pypmc run</code>.
      </p>

      <CodeBlock
        title="package.yml"
        code={`scripts:
  start: python main.py
  test: pytest --verbose
  lint: flake8 src/ --max-line-length=100
  format: black src/
  dev: flask run --debug --port 5000
  migrate: python manage.py migrate`}
        language="yaml"
      />

      <CodeBlock
        code={`pypmc run start     # python main.py\npypmc run test      # pytest --verbose\npypmc run lint      # flake8 src/ --max-line-length=100`}
        language="bash"
      />

      <p className="text-sm text-muted-foreground leading-relaxed mt-4">
        All scripts execute within the project's virtual environment. You can
        define up to 64 scripts. Script names are available as tab completions
        when shell completions are enabled.
      </p>
    </section>
  );
}
