name: pypmc-example-project
version: 1.0.0
description: this is an example project using pypmc
author: subhendu
license: MIT
python: 3.12
scripts:
  start: python main.py
  test: pytest
dependencies:
  flask: '==3.1.3'
dev_dependencies: {}
